import type { Metadata } from "next";
import { Inter, Playwrite_AR, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ThemeProvider } from "@/context/themeContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // একাধিক weight
  variable: "--font-inter",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "UpdateDesk",
  description: "Generated by Next.js, typescript, and shadcn",
  icons: {
    icon: "/favicon.png",
    apple: "/apple-touch-icon.png",
  },
};
export const playwrite = Playwrite_AR({
  style: ["normal"],
  variable: "--font-playwrite",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}    ${inter.className} antialiased`}>
        <ThemeProvider>
          <Navbar />
          {/* Main content of the application */}
          <div className="min-h-screen bg-gray-100 dark:bg-gray-900 text-gray-800 dark:text-gray-200">
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
